const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FF6B00",
    background: "#F2F2F7",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#FF6B00",
    primaryForeground: "#ffffff",
    secondary: "#E5E5EA",
    secondaryForeground: "#1a1a1a",
    muted: "#E5E5EA",
    mutedForeground: "#6D6D72",
    accent: "#FF6B00",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#C6C6C8",
    input: "#E5E5EA",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF6B00",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#FF6B00",
    primaryForeground: "#ffffff",
    secondary: "#2C2C2E",
    secondaryForeground: "#FFFFFF",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#FF6B00",
    accentForeground: "#ffffff",
    destructive: "#FF453A",
    destructiveForeground: "#ffffff",
    border: "#3A3A3C",
    input: "#2C2C2E",
  },
  radius: 12,
};

export default colors;
